export const todosConstants = {
  FETCH_REQUEST: 'TODOS_FETCH_REQUEST',
  FETCH_SUCCESS: 'TODOS_FETCH_SUCCESS',
  FETCH_ERROR:   'TODOS_FETCH_ERROR',

  CREATE_REQUEST: 'TODOS_CREATE_REQUEST',
  CREATE_SUCCESS: 'TODOS_CREATE_SUCCESS',
  CREATE_ERROR:   'TODOS_CREATE_ERROR',

  TOGGLE_REQUEST: 'TODOS_TOGGLE_REQUEST',
  TOGGLE_SUCCESS: 'TODOS_TOGGLE_SUCCESS',
  TOGGLE_ERORR:   'TODOS_TOGGLE_ERROR',
}
