export const todosConstants = {
  FETCH_REQUEST: 'TODOS_FETCH_REQUEST',
  FETCH_SUCCESS: 'TODOS_FETCH_SUCCESS',
  FETCH_ERROR:   'TODOS_FETCH_ERROR',

  CREATE: 'TODOS_CREATE',
  TOGGLE: 'TODOS_TOGGLE',
  RECEIVE: 'TODOS_RECEIVE',
  REQUEST: 'TODOS_REQUEST',
}
